name: 'Setup Environment'
description: 'Checks out code, sets up Node.js and Bun, caches dependencies, and installs them'
inputs:
  node-version:
    description: 'Node.js version'
    required: true
    default: '20'
  bun-version:
    description: 'Bun version'
    required: true
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org"

    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Cache Bun dependencies
      uses: actions/cache@v3
      with:
        path: ~/.bun/install/cache/v*/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}

    - name: Install dependencies
      run: bun install
      shell: bash
