version: "3.8"

services:
    dynamodb:
        image: amazon/dynamodb-local
        container_name: dynamodb-local
        ports:
            - "8000:8000"
        volumes:
            - dynamodb_data:/home/dynamodblocal/data

volumes:
    dynamodb_data:
