name: AI Code Reviewer

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
        paths-ignore:
            - '**/*.json'
            - '**/*.md'
permissions: write-all # Needed for AI reviewer
jobs:
    lint:
        runs-on: ubuntu-latest
        name: Lint Code
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Environment
              uses: ./.github/actions/setup
              with:
                  node-version: '20'
                  bun-version: 'latest'

            - name: Run linter
              run: bun run lint

    format:
        runs-on: ubuntu-latest
        name: Check Code Formatting
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Environment
              uses: ./.github/actions/setup
              with:
                  node-version: '20'
                  bun-version: 'latest'

            - name: Check code formatting
              run: bun run format:check

    build:
        runs-on: ubuntu-latest
        name: Build Project
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Environment
              uses: ./.github/actions/setup
              with:
                  node-version: '20'
                  bun-version: 'latest'

            - name: Build the project
              run: bun run build

    test:
        runs-on: ubuntu-latest
        name: Test Project
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Environment
              uses: ./.github/actions/setup
              with:
                  node-version: '20'
                  bun-version: 'latest'

            - name: Run tests
              run: bun run test

    review:
        runs-on: ubuntu-latest
        needs: [lint, format, build, test]
        if: github.event_name == 'pull_request'
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: AI Code Reviewer
              uses: freeedcom/ai-codereviewer@v2.7.0
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  OPENAI_API_MODEL: 'gpt-4'
                  exclude: '**/*.json, **/*.md'
